CREATE TABLE [dbo].[BoardAccess] (
    [Id] UNIQUEIDENTIFIER DEFAULT NEWID(),
    [Name] NVARCHAR (50) NOT NULL,
    [Description] NVARCHAR(250) NOT NULL, 
    CONSTRAINT [PK_BoardAccess] PRIMARY KEY CLUSTERED ([Id] ASC)
);
