CREATE TABLE [dbo].[Group]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWID(),
	[UserId] UNIQUEIDENTIFIER NOT NULL, /* FK User(id) */
	[Name] NVARCHAR(50) NOT NULL,
	[Color] NVARCHAR(7) NOT NULL, 
	CONSTRAINT [PK_Group] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_Group-UserId_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id]),
)
